<?php

return [
    /**
     * Thawani Pay Configuration.
     */
    [
        'key' => 'sales.payment_methods.oman_thawani',
        'name' => 'oman_payments::app.thawani.system_title',
        'info' => 'oman_payments::app.thawani.system_info',
        'sort' => 10,
        'fields' => [
            [
                'name' => 'title',
                'title' => 'admin::app.configuration.index.sales.payment-methods.title',
                'type' => 'text',
                'validation' => 'required',
                'channel_based' => false,
                'locale_based' => true,
            ],
            [
                'name' => 'description',
                'title' => 'admin::app.configuration.index.sales.payment-methods.description',
                'type' => 'textarea',
                'channel_based' => false,
                'locale_based' => true,
            ],
            [
                'name' => 'image',
                'title' => 'admin::app.configuration.index.sales.payment-methods.logo',
                'type' => 'image',
                'channel_based' => false,
                'locale_based' => false,
            ],
            [
                'name' => 'active',
                'title' => 'admin::app.configuration.index.sales.payment-methods.status',
                'type' => 'boolean',
                'validation' => 'required',
                'channel_based' => false,
                'locale_based' => false,
            ],
            [
                'name' => 'simulation_mode',
                'title' => 'oman_payments::app.fields.simulation_mode',
                'info' => 'oman_payments::app.fields.simulation_mode_info',
                'type' => 'boolean',
                'channel_based' => false,
                'locale_based' => false,
            ],
            [
                'name' => 'sandbox',
                'title' => 'admin::app.configuration.index.sales.payment-methods.sandbox',
                'type' => 'boolean',
                'channel_based' => false,
                'locale_based' => false,
            ],
            [
                'name' => 'public_key',
                'title' => 'oman_payments::app.thawani.public_key',
                'type' => 'text',
                'channel_based' => false,
                'locale_based' => false,
            ],
            [
                'name' => 'secret_key',
                'title' => 'oman_payments::app.thawani.secret_key',
                'type' => 'password',
                'channel_based' => false,
                'locale_based' => false,
            ],
            [
                'name' => 'sort',
                'title' => 'admin::app.configuration.index.sales.payment-methods.sort-order',
                'type' => 'select',
                'options' => [
                    ['title' => '1', 'value' => 1],
                    ['title' => '2', 'value' => 2],
                    ['title' => '3', 'value' => 3],
                    ['title' => '4', 'value' => 4],
                    ['title' => '5', 'value' => 5],
                    ['title' => '6', 'value' => 6],
                    ['title' => '7', 'value' => 7],
                    ['title' => '8', 'value' => 8],
                    ['title' => '9', 'value' => 9],
                    ['title' => '10', 'value' => 10],
                ],
            ],
        ],
    ],

    /**
     * Bank Muscat SmartPay Configuration.
     */
    [
        'key' => 'sales.payment_methods.oman_bankmuscat',
        'name' => 'oman_payments::app.bankmuscat.system_title',
        'info' => 'oman_payments::app.bankmuscat.system_info',
        'sort' => 11,
        'fields' => [
            [
                'name' => 'title',
                'title' => 'admin::app.configuration.index.sales.payment-methods.title',
                'type' => 'text',
                'validation' => 'required',
                'channel_based' => false,
                'locale_based' => true,
            ],
            [
                'name' => 'description',
                'title' => 'admin::app.configuration.index.sales.payment-methods.description',
                'type' => 'textarea',
                'channel_based' => false,
                'locale_based' => true,
            ],
            [
                'name' => 'image',
                'title' => 'admin::app.configuration.index.sales.payment-methods.logo',
                'type' => 'image',
                'channel_based' => false,
                'locale_based' => false,
            ],
            [
                'name' => 'active',
                'title' => 'admin::app.configuration.index.sales.payment-methods.status',
                'type' => 'boolean',
                'validation' => 'required',
                'channel_based' => false,
                'locale_based' => false,
            ],
            [
                'name' => 'simulation_mode',
                'title' => 'oman_payments::app.fields.simulation_mode',
                'info' => 'oman_payments::app.fields.simulation_mode_info',
                'type' => 'boolean',
                'channel_based' => false,
                'locale_based' => false,
            ],
            [
                'name' => 'sandbox',
                'title' => 'admin::app.configuration.index.sales.payment-methods.sandbox',
                'type' => 'boolean',
                'channel_based' => false,
                'locale_based' => false,
            ],
            [
                'name' => 'merchant_id',
                'title' => 'oman_payments::app.bankmuscat.merchant_id',
                'type' => 'text',
                'channel_based' => false,
                'locale_based' => false,
            ],
            [
                'name' => 'api_password',
                'title' => 'oman_payments::app.bankmuscat.api_password',
                'type' => 'password',
                'channel_based' => false,
                'locale_based' => false,
            ],
            [
                'name' => 'gateway_host',
                'title' => 'oman_payments::app.bankmuscat.gateway_host',
                'info' => 'oman_payments::app.bankmuscat.gateway_host_info',
                'type' => 'text',
                'channel_based' => false,
                'locale_based' => false,
            ],
            [
                'name' => 'api_version',
                'title' => 'oman_payments::app.bankmuscat.api_version',
                'type' => 'text',
                'channel_based' => false,
                'locale_based' => false,
            ],
            [
                'name' => 'sort',
                'title' => 'admin::app.configuration.index.sales.payment-methods.sort-order',
                'type' => 'select',
                'options' => [
                    ['title' => '1', 'value' => 1],
                    ['title' => '2', 'value' => 2],
                    ['title' => '3', 'value' => 3],
                    ['title' => '4', 'value' => 4],
                    ['title' => '5', 'value' => 5],
                    ['title' => '6', 'value' => 6],
                    ['title' => '7', 'value' => 7],
                    ['title' => '8', 'value' => 8],
                    ['title' => '9', 'value' => 9],
                    ['title' => '10', 'value' => 10],
                ],
            ],
        ],
    ],

    /**
     * AmwalPay Configuration.
     */
    [
        'key' => 'sales.payment_methods.oman_amwal',
        'name' => 'oman_payments::app.amwal.system_title',
        'info' => 'oman_payments::app.amwal.system_info',
        'sort' => 12,
        'fields' => [
            [
                'name' => 'title',
                'title' => 'admin::app.configuration.index.sales.payment-methods.title',
                'type' => 'text',
                'validation' => 'required',
                'channel_based' => false,
                'locale_based' => true,
            ],
            [
                'name' => 'description',
                'title' => 'admin::app.configuration.index.sales.payment-methods.description',
                'type' => 'textarea',
                'channel_based' => false,
                'locale_based' => true,
            ],
            [
                'name' => 'image',
                'title' => 'admin::app.configuration.index.sales.payment-methods.logo',
                'type' => 'image',
                'channel_based' => false,
                'locale_based' => false,
            ],
            [
                'name' => 'active',
                'title' => 'admin::app.configuration.index.sales.payment-methods.status',
                'type' => 'boolean',
                'validation' => 'required',
                'channel_based' => false,
                'locale_based' => false,
            ],
            [
                'name' => 'simulation_mode',
                'title' => 'oman_payments::app.fields.simulation_mode',
                'info' => 'oman_payments::app.fields.simulation_mode_info',
                'type' => 'boolean',
                'channel_based' => false,
                'locale_based' => false,
            ],
            [
                'name' => 'sandbox',
                'title' => 'admin::app.configuration.index.sales.payment-methods.sandbox',
                'type' => 'boolean',
                'channel_based' => false,
                'locale_based' => false,
            ],
            [
                'name' => 'merchant_id',
                'title' => 'oman_payments::app.amwal.merchant_id',
                'type' => 'text',
                'channel_based' => false,
                'locale_based' => false,
            ],
            [
                'name' => 'terminal_id',
                'title' => 'oman_payments::app.amwal.terminal_id',
                'type' => 'text',
                'channel_based' => false,
                'locale_based' => false,
            ],
            [
                'name' => 'secret_key',
                'title' => 'oman_payments::app.amwal.secret_key',
                'type' => 'password',
                'channel_based' => false,
                'locale_based' => false,
            ],
            [
                'name' => 'sort',
                'title' => 'admin::app.configuration.index.sales.payment-methods.sort-order',
                'type' => 'select',
                'options' => [
                    ['title' => '1', 'value' => 1],
                    ['title' => '2', 'value' => 2],
                    ['title' => '3', 'value' => 3],
                    ['title' => '4', 'value' => 4],
                    ['title' => '5', 'value' => 5],
                    ['title' => '6', 'value' => 6],
                    ['title' => '7', 'value' => 7],
                    ['title' => '8', 'value' => 8],
                    ['title' => '9', 'value' => 9],
                    ['title' => '10', 'value' => 10],
                ],
            ],
        ],
    ],

    /**
     * Paymob Oman Configuration.
     */
    [
        'key' => 'sales.payment_methods.oman_paymob',
        'name' => 'oman_payments::app.paymob.system_title',
        'info' => 'oman_payments::app.paymob.system_info',
        'sort' => 13,
        'fields' => [
            [
                'name' => 'title',
                'title' => 'admin::app.configuration.index.sales.payment-methods.title',
                'type' => 'text',
                'validation' => 'required',
                'channel_based' => false,
                'locale_based' => true,
            ],
            [
                'name' => 'description',
                'title' => 'admin::app.configuration.index.sales.payment-methods.description',
                'type' => 'textarea',
                'channel_based' => false,
                'locale_based' => true,
            ],
            [
                'name' => 'image',
                'title' => 'admin::app.configuration.index.sales.payment-methods.logo',
                'type' => 'image',
                'channel_based' => false,
                'locale_based' => false,
            ],
            [
                'name' => 'active',
                'title' => 'admin::app.configuration.index.sales.payment-methods.status',
                'type' => 'boolean',
                'validation' => 'required',
                'channel_based' => false,
                'locale_based' => false,
            ],
            [
                'name' => 'simulation_mode',
                'title' => 'oman_payments::app.fields.simulation_mode',
                'info' => 'oman_payments::app.fields.simulation_mode_info',
                'type' => 'boolean',
                'channel_based' => false,
                'locale_based' => false,
            ],
            [
                'name' => 'sandbox',
                'title' => 'admin::app.configuration.index.sales.payment-methods.sandbox',
                'type' => 'boolean',
                'channel_based' => false,
                'locale_based' => false,
            ],
            [
                'name' => 'api_key',
                'title' => 'oman_payments::app.paymob.api_key',
                'type' => 'password',
                'channel_based' => false,
                'locale_based' => false,
            ],
            [
                'name' => 'integration_id',
                'title' => 'oman_payments::app.paymob.integration_id',
                'type' => 'text',
                'channel_based' => false,
                'locale_based' => false,
            ],
            [
                'name' => 'iframe_id',
                'title' => 'oman_payments::app.paymob.iframe_id',
                'type' => 'text',
                'channel_based' => false,
                'locale_based' => false,
            ],
            [
                'name' => 'hmac_secret',
                'title' => 'oman_payments::app.paymob.hmac_secret',
                'type' => 'password',
                'channel_based' => false,
                'locale_based' => false,
            ],
            [
                'name' => 'sort',
                'title' => 'admin::app.configuration.index.sales.payment-methods.sort-order',
                'type' => 'select',
                'options' => [
                    ['title' => '1', 'value' => 1],
                    ['title' => '2', 'value' => 2],
                    ['title' => '3', 'value' => 3],
                    ['title' => '4', 'value' => 4],
                    ['title' => '5', 'value' => 5],
                    ['title' => '6', 'value' => 6],
                    ['title' => '7', 'value' => 7],
                    ['title' => '8', 'value' => 8],
                    ['title' => '9', 'value' => 9],
                    ['title' => '10', 'value' => 10],
                ],
            ],
        ],
    ],
];
